### ISSUE TITLE
Configurable Port question

### ISSUE THREAD

**Issue by dgracehmh** [pact-foundation/pact-broker-docker#1]
# Pre issue-raising checklist

I have already (please mark the applicable with an `x`):

* [x ] Confirmed this is the right place to raise the issue - only issues related to the Dockerization of the Pact Broker should be raised here. Issues related to the Pact Broker application itself should be raised in the [Pact Broker](https://github.com/pact-foundation/pact_broker) project.
* [x ] Upgraded to the latest Pact Broker Docker image OR
* [x ] Checked the [CHANGELOG](/CHANGELOG.md) to see if the issue I am about to raise has been fixed
* [x ] Read the [Troubleshooting](https://github.com/pact-foundation/pact-broker-docker/wiki/Troubleshooting) page

## Software versions

* **pact-broker gem version:** eg 2.3.1
* **pact-broker docker version:** eg 2.3.1-1
* **OS**: e.g. Mac OSX 10.11.5
* **pact broker client details:** eg. pact-ruby-standalone CLI v 1.23.0

## Expected behaviour

Hi, This is more a query than an issue. Is there a way to configure the port that Pact Broker is running on in the Docker container to be something other than 9292? 
As a background I want to run a Dockerised Pact Broker in Apache Mesos/aurora. To do that I need to startup the container with a random port number that gets assigned by mesos. This is generally passed to an environment variable for Port. I've trawled through older issues etc but cannot figure out if this is supported. 

I noticed in here - https://github.com/pact-foundation/pact-broker-docker/blob/master/script/test.sh#L56 - PACT_BROKER_PORT but i dont think this is what i need.

Thanks for the help and for a great tool!

## Actual behaviour

TBC

## Steps to reproduce

Provide a repository, gist or reproducable code snippet so that we can test the problem.

## Relevent log files

Please ensure you set logging to `DEBUG` and attach any relevant log files here (or link from a gist).

**Comment by bethesque** [comment]
You can't map it to the port you want from the outside? It seems strange to me that the internal port makes a difference.

**Comment by bethesque** [comment]
I believe we may be able to do it like this (disclaimer, I never actually tested that this worked): https://github.com/pact-foundation/pact-mock-service-docker/pull/3/files

**Comment by dgracehmh** [comment]
@bethesque yes, this is how Apache aurora handles service discovery - http://aurora.apache.org/documentation/latest/features/services/ 
It assigns a http port (could be anything) to the process and that port is passed as a startup parameter to the application. e.g.
```
nginx = Process(
  name = 'nginx',
  cmdline = './run_nginx.sh -port {{thermos.ports[http]}}'
)
```
The port could also be set as an environment var like the example you mentioned above. 
Do you know if the pact broker supports passing port as a parameter (outside docker implementation)?

**Comment by dgracehmh** [comment]
Just did a little digging, looks like puma supports different ports - https://github.com/puma/puma/blob/master/lib/puma/dsl.rb#L152

If I get time I will look into the sourcecode for PactBroker. I've never coded in Ruby so it might be slow :)
