### ISSUE TITLE
Update ./script/test.sh to use docker compose or sqlite

### ISSUE THREAD

**Issue by bethesque** [pact-foundation/pact-broker-docker#10]
The current script/test.sh uses very old docker code to provide a postgres database to run against. This can be changed to use a sqlite instance, or use docker-compose to provide a postgres database.

**Comment by YOU54F** [comment]
Completed in https://github.com/pact-foundation/pact-broker-docker/commit/fb3c89fa7fada7f80222a41fd23653e83c5ebea4
