### ISSUE TITLE
Upgrade to Alpine Linux ver 3.17

### ISSUE THREAD

**Issue by jorander** [pact-foundation/pact-broker-docker#104]
# Pre issue-raising checklist

I have already (please mark the applicable with an `x`):

* [x] Confirmed this is the right place to raise the issue - only issues related to the Dockerization of the Pact Broker should be raised here. Issues related to the Pact Broker application itself should be raised in the [Pact Broker](https://github.com/pact-foundation/pact_broker) project.
* [x] Upgraded to the latest Pact Broker Docker image OR
* [x] Checked the [CHANGELOG](/CHANGELOG.md) to see if the issue I am about to raise has been fixed
* [x] Read the [Troubleshooting](https://github.com/pact-foundation/pact-broker-docker/wiki/Troubleshooting) page

## Software versions

* **pact-broker gem version:** 2.106.0
* **pact-broker docker version:** 2.106.0.0

## Expected behaviour

Use Alpine Linux 3.17 to avoid security issues related to version 3.16.

## Actual behaviour

Alpine Linux 3.16 contains several packages (mariadb-deb, sqlite, libxml2) with reported CVE:s with severity level Critical and High.

## Steps to reproduce

Scan the docker image with Jfrog Xray.

## Relevent log files

N/A

**Comment by jorander** [comment]
Upgrade to Alpine Linux 3.17 requires Pact-Broker to be upgraded to at least Ruby 3.1.3. This is since there is no official Ruby image based on Alpine 3.17 before Ruby 3.1.3.

**Comment by mefellows** [comment]
Note: the Ruby 3 upgrade is progressing well over in PactFlow land. We test out many new features/changes on that platform before introducing into the OSS code base.

Stay tuned for further updates in relation to this, I'd expect within ~1 month or so for us to be able to provide a clearer line of sight as to when we can move forward with the change here.

**Comment by bethesque** [comment]
The image is out with `ruby:3.2.1-alpine3.17` base.
