### ISSUE TITLE
Port env variable is mandatory, error thrown if not provided

### ISSUE THREAD

**Issue by AndrewGrachov** [pact-foundation/pact-broker-docker#14]
**Image version** 2.42.0-1

**ENV:* kubernetes

**Error shown:**

```
bundler: failed to load command: puma (/pact_broker/vendor/bundle/ruby/2.6.0/bin/puma)
URI::InvalidURIError: bad URI(is not URI?): "tcp://0.0.0.0:tcp://100.68.190.5:22"
```

**fixed by:**

Providing **PACT_BROKER_PORT** environment variable

**Suggested solution** :

- add default parameter, or specify in docs

**Comment by bethesque** [comment]
I don't see how it can not be set, as the Dockerfile has `ENV PACT_BROKER_PORT=9292` 🤔

**Comment by bethesque** [comment]
I don't know if there's anything different about running it with docker-compose, but if I delete `PACT_BROKER_PORT: "9292"` from the docker-compose file and then do `docker-compose up --build` it runs fine. Can you provide a docker compose file to reproduce the issue?

**Comment by AndrewGrachov** [comment]
Sorry, forgot to mention it, this happens inside kubernetes, docker-compose is ok

**Comment by bethesque** [comment]
I'm afraid I don't know why Kubernetes would run any differently. As you can see, the Dockerfile provides a default value. Can you think of anything else that could be done? Perhaps this is a question that needs to be followed up with the Kubernetes community.

**Comment by lpdeveloper** [comment]
I think that the port mentioned inside the Dockerfile is the port where pact-broker will run inside the container. 
But In K8s by providing `PACT_BROKER_PORT: "9292"` we are giving the port where pact-broker will run/bind in the K8s pod.

**Comment by rndmh3ro** [comment]
I can confirm the error (in Openshift, too) and the solution to set the `PACT_BROKER_PORT` environment variable.

**Comment by bethesque** [comment]
Is it possible that this is related? https://github.com/pact-foundation/pact-broker-docker/issues/7 What if you change the name of the kubernetes "thing" to something that is not "pact_broker" or "pact-broker"?

**Comment by rndmh3ro** [comment]
Yes, this seems related. Kubernetes sets some environment-variables by default in the container: https://kubernetes.io/docs/concepts/containers/container-environment-variables/#cluster-information

> A list of all services that were running when a Container was created is available to that Container as environment variables. Those environment variables match the syntax of Docker links.
> 
> For a service named foo that maps to a Container named bar, the following variables are defined:
> 
> FOO_SERVICE_HOST=<the host the service is running on>
> FOO_SERVICE_PORT=<the port the service is running on>

So if you create a service with the name `pact-broker` (reasonable in kubernetes), the following env-variable will be created in the container: `PACT_BROKER_PORT=tcp://10.128.143.221:8080`.

Coincidentally the same name that was defined in this project.

**Comment by bethesque** [comment]
It is the obvious name to pick! I think you'll have to give the kube service a different name unfortunately.

**Comment by rndmh3ro** [comment]
I'm okay with that. How about adding to the docs that you have to do this in order to run pact on k8s?

**Comment by bethesque** [comment]
Done. https://github.com/pact-foundation/pact-broker-docker#running-on-kubernetes

**Comment by bethesque** [comment]
@rndmh3ro should I do the same documentation as linked above for OpenShift?

**Comment by rndmh3ro** [comment]
Yes, the same thing applies for openshift. Thank you for taking the time to do this!

**Comment by bethesque** [comment]
Done.
