### ISSUE TITLE
Mysql2 cannot load lib/mariadb/plugin/caching_sha2_password.so

### ISSUE THREAD

**Issue by seaniefs** [pact-foundation/pact-broker-docker#18]
# Pre issue-raising checklist

I have already (please mark the applicable with an `x`):

* [X] Confirmed this is the right place to raise the issue - only issues related to the Dockerization of the Pact Broker should be raised here. Issues related to the Pact Broker application itself should be raised in the [Pact Broker](https://github.com/pact-foundation/pact_broker) project.
* [X] Upgraded to the latest Pact Broker Docker image OR
* [X] Checked the [CHANGELOG](/CHANGELOG.md) to see if the issue I am about to raise has been fixed
* [X] Read the [Troubleshooting](https://github.com/pact-foundation/pact-broker-docker/wiki/Troubleshooting) page

## Software versions

* **pact-broker gem version:** 3.12.2
* **pact-broker docker version:**  2.50.1-1
* **OS**: e.g. Mac OSX 10.11.5
* **pact broker client details:** N/A

## Expected behaviour

When running pact-broker with the following environment variables:
<pre>
      PACT_BROKER_DATABASE_ADAPTER: mysql2
      PACT_BROKER_DATABASE_USERNAME: pactusername
      PACT_BROKER_DATABASE_PASSWORD: pactpassword
      PACT_BROKER_DATABASE_HOST: mysql
      PACT_BROKER_DATABASE_NAME: pact
      PACT_BROKER_DATABASE_PORT: 3306
</pre>

I would expect the pact broker to start-up without any issues.

## Actual behaviour

The pact-broker fails to start with the following error:
<pre>
Sequel::DatabaseConnectionError: Mysql2::Error: Plugin caching_sha2_password could not be loaded: Error loading shared library lib/mariadb/plugin/caching_sha2_password.so: No such file or directory
</pre>

## Steps to reproduce

Use the following docker-compose:
<pre>
version: '3.3'
services:
  mysql:
    image: mysql
    ports:
    - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pact
      MYSQL_USER: pactusername
      MYSQL_PASSWORD: pactpassword
    volumes:
    - db_data:/var/lib/mysql
  pact-broker:
    image: pactfoundation/pact-broker
    ports:
    - "9292:9292"
    depends_on:
    - "mysql"
    restart: always
    environment:
      PACT_BROKER_DATABASE_ADAPTER: mysql2
      PACT_BROKER_DATABASE_USERNAME: pactusername
      PACT_BROKER_DATABASE_PASSWORD: pactpassword
      PACT_BROKER_DATABASE_HOST: mysql
      PACT_BROKER_DATABASE_NAME: pact
      PACT_BROKER_DATABASE_PORT: 3306
volumes:
  db_data:
</pre>

Run:

<code>docker-compose up -d</code>

## Relevent log files

The following log is generated:
<pre>
Puma starting in single mode...
* Version 3.12.2 (ruby 2.6.4-p104), codename: Llamas in Pajamas
* Min threads: 0, max threads: 16
* Environment: production
! Unable to load application: Sequel::DatabaseConnectionError: Mysql2::Error: Plugin caching_sha2_password could not be loaded: Error loading shared library lib/mariadb/plugin/caching_sha2_password.so: No such file or directory
bundler: failed to load command: puma (/pact_broker/vendor/bundle/ruby/2.6.0/bin/puma)
Sequel::DatabaseConnectionError: Mysql2::Error: Plugin caching_sha2_password could not be loaded: Error loading shared library lib/mariadb/plugin/caching_sha2_password.so: No such file or directory
  /pact_broker/vendor/bundle/ruby/2.6.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:90:in `connect'
  /pact_broker/vendor/bundle/ruby/2.6.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:90:in `initialize'
  /pact_broker/vendor/bundle/ruby/2.6.0/gems/sequel-5.29.0/lib/sequel/adapters/mysql2.rb:43:in `new'
  /pact_broker/vendor/bundle/ruby/2.6.0/gems/sequel-5.29.0/lib/sequel/adapters/mysql2.rb:43:in `connect'
  /pact_broker/vendor/bundle/ruby/2.6.0/gems/sequel-5.29.0/lib/sequel/connection_pool.rb:122:in `make_new'
  /pact_broker/vendor/bundle/ruby/2.6.0/gems/sequel-5.29.0/lib/sequel/connection_pool/threaded.rb:209:in `assign_connection'
  /pact_broker/vendor/bundle/ruby/2.6.0/gems/sequel-5.29.0/lib/sequel/connection_pool/threaded.rb:139:in `acquire'
  /pact_broker/vendor/bundle/ruby/2.6.0/gems/sequel-5.29.0/lib/sequel/connection_pool/threaded.rb:91:in `hold'
  /pact_broker/vendor/bundle/ruby/2.6.0/gems/sequel-5.29.0/lib/sequel/database/connecting.rb:270:in `synchronize'
  /pact_broker/vendor/bundle/ruby/2.6.0/gems/sequel-5.29.0/lib/sequel/database/connecting.rb:279:in `test_connection'
  /pact_broker/vendor/bundle/ruby/2.6.0/gems/sequel-5.29.0/lib/sequel/database/connecting.rb:58:in `connect'
  /pact_broker/vendor/bundle/ruby/2.6.0/gems/sequel-5.29.0/lib/sequel/core.rb:121:in `connect'
  /pact_broker/database_connection.rb:43:in `create_database_connection'
  config.ru:13:in `block (2 levels) in <main>'
  /pact_broker/vendor/bundle/ruby/2.6.0/gems/pact_broker-2.50.1/lib/pact_broker/app.rb:33:in `initialize'
  config.ru:11:in `new'
  config.ru:11:in `block in <main>'
  /pact_broker/vendor/bundle/ruby/2.6.0/gems/rack-2.2.2/lib/rack/builder.rb:116:in `eval'
  /pact_broker/vendor/bundle/ruby/2.6.0/gems/rack-2.2.2/lib/rack/builder.rb:116:in `new_from_string'
  /pact_broker/vendor/bundle/ruby/2.6.0/gems/rack-2.2.2/lib/rack/builder.rb:105:in `load_file'
  /pact_broker/vendor/bundle/ruby/2.6.0/gems/rack-2.2.2/lib/rack/builder.rb:66:in `parse_file'
  /pact_broker/vendor/bundle/ruby/2.6.0/gems/puma-3.12.2/lib/puma/configuration.rb:320:in `load_rackup'
  /pact_broker/vendor/bundle/ruby/2.6.0/gems/puma-3.12.2/lib/puma/configuration.rb:245:in `app'
  /pact_broker/vendor/bundle/ruby/2.6.0/gems/puma-3.12.2/lib/puma/runner.rb:147:in `load_and_bind'
  /pact_broker/vendor/bundle/ruby/2.6.0/gems/puma-3.12.2/lib/puma/single.rb:98:in `run'
  /pact_broker/vendor/bundle/ruby/2.6.0/gems/puma-3.12.2/lib/puma/launcher.rb:186:in `run'
  /pact_broker/vendor/bundle/ruby/2.6.0/gems/puma-3.12.2/lib/puma/cli.rb:80:in `run'
  /pact_broker/vendor/bundle/ruby/2.6.0/gems/puma-3.12.2/bin/puma:10:in `<top (required)>'
  /pact_broker/vendor/bundle/ruby/2.6.0/bin/puma:23:in `load'
  /pact_broker/vendor/bundle/ruby/2.6.0/bin/puma:23:in `<top (required)>'
</pre>

__NOTE:__

I found that I was able to work around the issue by linking <code>/usr/lib/mariadb</code> to <code>$HOME/lib/mariadb</code> in the docker image - but it's pretty ugly...

**Comment by bethesque** [comment]
You must be the first person to try the new puma image with MySQL. We'll fix it, but can I very strongly suggest you use Postgres if possible? MySQL has limitations that affect the performance of the broker.

**Comment by bethesque** [comment]
Have you tried this? It seems there are different password modes https://stackoverflow.com/questions/49194719/authentication-plugin-caching-sha2-password-cannot-be-loaded

**Comment by seaniefs** [comment]
@bethesque Thanks for the reply - it's much appreciated.  We had some strange constraint violations when using PostgreSQL (I will try and raise on the pact-broker project), hence the move to MySQL.

So far, our initial tests indicate that once the link was added, all seems to be well for now.

**Comment by bethesque** [comment]
Please do let me know what the issue was with postgres. It should be able to be resolved. We run hundreds of tenants on pactflow.io (a commercial fork of the broker) on Postgres without any issues.
