### ISSUE TITLE
Client.Timeout exceeded while awaiting headers

### ISSUE THREAD

**Issue by nitish-dubey** [pact-foundation/pact-broker-docker#2]
# Pre issue-raising checklist

I have already (please mark the applicable with an `x`):

* [X ] Confirmed this is the right place to raise the issue - only issues related to the Dockerization of the Pact Broker should be raised here. Issues related to the Pact Broker application itself should be raised in the [Pact Broker](https://github.com/pact-foundation/pact_broker) project.
* [X] Upgraded to the latest Pact Broker Docker image OR
* [ ] Checked the [CHANGELOG](/CHANGELOG.md) to see if the issue I am about to raise has been fixed
* [ ] Read the [Troubleshooting](https://github.com/pact-foundation/pact-broker-docker/wiki/Troubleshooting) page

## Software versions

* **pact-broker gem version:** eg 2.3.1 . 2.5.2.3
* **pact-broker docker version:** eg 2.3.1-1
* **OS**: e.g. Mac OSX 10.11.5 Mac OSX  10.14.4
* **pact broker client details:** eg. pact-ruby-standalone CLI v 1.23.0

## Expected behaviour

Successfully run container

## Actual behaviour

Getting error
ERROR: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

I updated dius/pact-broker to pactfoundation/pact-broker

 broker_app:
    image: pactfoundation/pact-broker
    links:
      - postgres
    # If you remove nginx, enable the following
    ports:
      - "8585:80"
    environment:
      PACT_BROKER_DATABASE_USERNAME: username
      PACT_BROKER_DATABASE_PASSWORD: password
      PACT_BROKER_DATABASE_HOST: postgres
      PACT_BROKER_DATABASE_NAME: postgres
      PACT_BROKER_LOG_LEVEL: DEBUG

## Steps to reproduce

Provide a repository, gist or reproducable code snippet so that we can test the problem.

## Relevent log files

Please ensure you set logging to `DEBUG` and attach any relevant log files here (or link from a gist).

**Comment by bethesque** [comment]
This appears to be a docker hub issue.
