### ISSUE TITLE
Docker tag for major versions

### ISSUE THREAD

**Issue by artheus** [pact-foundation/pact-broker-docker#24]
I have already:

* [x] Confirmed this is the right place to raise the issue - only issues related to the Dockerization of the Pact Broker should be raised here. Issues related to the Pact Broker application itself should be raised in the [Pact Broker](https://github.com/pact-foundation/pact_broker) project.
* [x] Upgraded to the latest Pact Broker Docker image OR
* [x] Checked the [CHANGELOG](/CHANGELOG.md) to see if the issue I am about to raise has been fixed
* [x] Read the [Troubleshooting](https://github.com/pact-foundation/pact-broker-docker/wiki/Troubleshooting) page

## Software versions

* **pact-broker gem version:** N/A
* **pact-broker docker version:** 2.x.x
* **OS**: N/A
* **pact broker client details:** N/A

## Expected behaviour

Docker tags for major versions of pact-broker (e.g. `2` for latest release of major version 2)

This would be preferable, since the major version might change in the future,
which usually implies breaking changes (e.g. no longer backwards compatible with major version 2 database)

If we, at my workplace, want to automatically trigger deployment of latest version (w/o breaking stuff). We would feel much safer if we had the ability to stick to a major version of the pact-broker, without worrying to much.

## Actual behaviour

Only full version numbers, `latest` and `edge` are available.

## Steps to reproduce

N/A

## Relevant log files

N/A

**Comment by bethesque** [comment]
That can be done pretty easily.

**Comment by bethesque** [comment]
Ok, you should see a `2` tag in docker hub now.
