### ISSUE TITLE
Matrix not always returning Latest version with tag

### ISSUE THREAD

**Issue by anto-ac** [pact-foundation/pact-broker-docker#28]
I am raising an issue as suggested by @mefellows, however I don’t have the precise steps to reproduce it right now. It’s happening consistently for some of our participants, so it might be due to a specific state of our data.

Pacticipant has multiple versions tagged as master. When on the matrix I choose to see the latest version with tag master for that pacticipant, nothing is returned. When I ask for all versions with tag master, all versions tagged as master are returned, including the latest. However, the latest master tag is not marked as blue (I assume indicates that it’s the latest version for a tag).

The same happens when invoking can I deploy for a provider of that participant with latest=master

Finding the latest version tagged as master for that pacticipant directly via the API returns the expected version though.

We have been trying to debug through the broker using a dump of our database but we have only got round to running the broker locally using the dev example pointing to a restored db. Ideally we want to run the broker via the codebase and not the gem in order to debug.

**Comment by bethesque** [comment]
@anto-ac can you do an export of your database, and then redact it using [this script](https://github.com/pact-foundation/pact_broker/blob/master/script/prod/redact-data.sql) and send it to me.

It will help if you make note of the ids of the problem pacticipants before you redact them, so you can find them afterwards to recreate the issue.

**Comment by bethesque** [comment]
If you've cleaned up some data recently, there's something that might possibly have happened. You might be in the situation where the latest application version with the master tag does not actually have a pact. So the "latest app version with the master tag" might not be the same as "the latest app version with the master tag that has a pact". I'm very much speculating here though. I should be able to debug it very easily if I have your data.

**Comment by anto-ac** [comment]
Thanks @bethesque !

I don’t think the script will be enough to redact everything in our case as we’d have to also redact the versions, some of them have branch names in them.

**Comment by bethesque** [comment]
Well update the script to redact the versions too :P

**Comment by bethesque** [comment]
https://github.com/pact-foundation/pact_broker/commit/965cbbdcd1bb9b35b299d4dbcc5b4a88dec1f6c3

**Comment by anto-ac** [comment]
Not sure why I ever opened this in this repo to be honest, probably due some bad googling on my side.

Anyway, I am happy to close this as this was happening because consumer and provider were using two different versions. Versions need to match for this to work.
