### ISSUE TITLE
Add support for PACT_BROKER_WEBHOOK_RETRY_SCHEDULE environment variable

### ISSUE THREAD

**Issue by pitschr** [pact-foundation/pact-broker-docker#35]
# Pre issue-raising checklist

I have already (please mark the applicable with an `x`):

* [x] Confirmed this is the right place to raise the issue - only issues related to the Dockerization of the Pact Broker should be raised here. Issues related to the Pact Broker application itself should be raised in the [Pact Broker](https://github.com/pact-foundation/pact_broker) project.
* [x] Upgraded to the latest Pact Broker Docker image OR
* [x] Checked the [CHANGELOG](/CHANGELOG.md) to see if the issue I am about to raise has been fixed
* [x] Read the [Troubleshooting](https://github.com/pact-foundation/pact-broker-docker/wiki/Troubleshooting) page

## Software versions

* **pact-broker docker version:** docker.io/pactfoundation/pact-broker:2.68.1.0

## Expected behaviour

`PactBroker.configuration.webhook_retry_schedule` should be set by `PACT_BROKER_WEBHOOK_RETRY_SCHEDULE`

## Actual behaviour

`PACT_BROKER_WEBHOOK_RETRY_SCHEDULE` has no effect and seems be unsupported

## Steps to reproduce

Start docker with environment variable `PACT_BROKER_WEBHOOK_RETRY_SCHEDULE` to change the retry setting.

## Relevent log files

```
2021-01-20 11:40:48.579667 I [6:47327367469560] pact-broker -- PactBroker.configuration.webhook_retry_schedule=[10, 60, 120, 300, 600, 1200]
```

## Background

We are facing same issue reported here:
https://github.com/pact-foundation/pact_broker/issues/239

As CI/CD we are using Bamboo and when all Bamboo Agent are busy then it returns "400" 
https://docs.atlassian.com/atlassian-bamboo/REST/6.10.4/#d2e5357 which may keep triggering the build plan again and again. As workaround we would switch off the retry, as the request is already added/registered, just it will be executed as soon as one bamboo agent is free again.

**Comment by bethesque** [comment]
Would you like to raise a PR for this? It should be a simple change, and I like to get more people across the codebase and able to contribute.

**Comment by pitschr** [comment]
Hi Beth.

I have raised a PR request ( my first time with Ruby ).

Example:
`PACT_BROKER_WEBHOOK_RETRY_SCHEDULE=1 2 3 4 5` will be translated to 
```
PactBroker.configuration.webhook_retry_schedule=[1, 2, 3, 4, 5]
```

If a non-integer is provided, it will be simply ignored, this means e.g. `PACT_BROKER_WEBHOOK_RETRY_SCHEDULE=1 2 foo 4 5` will result into 
```
PactBroker.configuration.webhook_retry_schedule=[1, 2, 4, 5]
```

In the Pull Request there is one task calling "Semantic Pull Request" failing. Can you please advise what needs to be there? I have already changed the title to "feat/35 ..."

**Comment by bethesque** [comment]
@pitschr you did so well with the environment variable fix, even though you didn't know Ruby. Want to have a crack at implementing the real fix? The webhook needs an extra property which specifies which http statuses should be considered a success. It shouldn't be a lot of work, but it's such a niche issue that it's unlikely to ever reach the top of my priority stack.

**Comment by pitschr** [comment]
I would give a try, but I am stuck somehow. What I have done so far:

1. Forked from https://github.com/pact-foundation/pact_broker and clone project into IntelliJ and prepared for Ruby SDK
2. Installed some gems using `bundler install` (here I had to fix several issues e.g. switch from `rvm` to `rbenv`)
3. Replace lines with `require 'pact_broker...'`  to `require 'lib/pact_broker...'` as the path seems be incorrect -> complaint from IntelliJ and references are not working
4. Created `tmp` to allow to create a sqlite3 file (otherwise it end up with `SQLite3::CantOpenException`)
5. Run rspec and it ends with and here I'm stuck:
```
SQLite3::SQLException: no such table: version_sequence_number
```

I guess there must be a magic that fills the database automatically as I have seen some files in `db/migrations` folder, but for some reasons it is not called. Perhaps I have overlooked some files which needs a manual correction....  no clue ...

My question:
Do you have a documentation how to prepare the pact-broker project for IDE (e.g. IntelliJ) to help me and other developers onboarded? When I clone the project from GIT repository using IntelliJ then I need to configure & prepare the project by myself to start with it. And here many things can go wrong.

**Comment by bethesque** [comment]
Have you read the DEVELOPER_SETUP.md file? https://github.com/pact-foundation/pact_broker/blob/master/DEVELOPER_SETUP.md#running-the-tests You need to run `bundle exec rake db:prepare:test` first (or just run `bundle exec rake` which will set up and run everything).

The DEVELOPER_DOCUMENTATION.md is also a must read https://github.com/pact-foundation/pact_broker/blob/master/DEVELOPER_DOCUMENTATION.md There's a section on adding a resource that will describe all the files you need to touch, but you'll only have to add a field, so it should be simpler.

I use Sublime Text, so I'm afraid I can't help you with your IDE. Don't change the require to 'lib/pact_broker' - you need to add `./lib` to your path (however that's done in IntelliJ).

Happy to help out, it's great to have you on board! You might be better off hoping on to our slack (join at https://slack.pact.io) to ask questions. There will be people in the #pact-ruby channel who can answer your Ruby questions when I'm asleep (I live in Australia).

**Comment by bethesque** [comment]
This might be helpful, though it looks like you've already gotten past that stage https://www.jetbrains.com/help/idea/set-up-a-ruby-development-environment.html

**Comment by pitschr** [comment]
Thanks very much. I managed to run it. The `bundle exec rake db:prepare:test` solved the issue which made me crazy yesterday.  I have not seen those two MD files, was just reading the usual README.MD ;-) 

For IntelliJ I figured out that I have to select "lib" as "Load Path Root" so that references in IntelliJ are working.

**Comment by bethesque** [comment]
Awesome! Yeah, the README is very much focussed on the users, not the developers.

**Comment by pitschr** [comment]
This issue is considered as closed as the environment variable PACT_BROKER_WEBHOOK_RETRY_SCHEDULE is now supported
