### ISSUE TITLE
Add support for PACT_BROKER_WEBHOOK_HTTP_CODE_SUCCESS environment variable

### ISSUE THREAD

**Issue by pitschr** [pact-foundation/pact-broker-docker#38]
## Feature request

Add `PACT_BROKER_WEBHOOK_HTTP_CODE_SUCCESS` environment for docker to control: `PactBroker.Configuration. webhook_http_code_success` variable.

## As is

Currently the allowed http code is hardcoded with < 300. Meaning, 1xx HTTP code family and 2xx HTTP code family are allowed.

## To be

With Pull Request merge we are adding configuration for 'webhook_http_code_whitelist': 
https://github.com/pact-foundation/pact_broker/pull/386 <== ALREADY MERGED

We should also add environment variable for `PACT_BROKER_WEBHOOK_HTTP_CODE_SUCCESS` to allow docker users to customize the list of allowed HTTP codes for webhook.

## History of webhook http code success list

Bamboo Agent has a strange behavior when triggering a provider build plan and the bamboo agent is busy, then it will return a   HTTP Code 400 despite that the execution of provider build plan has been added to the queue already. It will just be executed as soon the agent is free.

Retry of webhook triggers based on http code for 2xx may have a bad effect because it will keep triggering the plans until the number of retries is reached. For Bamboo users the successful http codes should be: `[200, 400]`

Further reference:
http://docs.atlassian.com/atlassian-bamboo/REST/7.2.2/#d2e6123

**Comment by pitschr** [comment]
@bethesque , I have prepared the PR on my local machine. However, it fails with 

```
bundler: failed to load command: puma (/pact_broker/vendor/bundle/ruby/2.6.0/bin/puma)
NoMethodError: undefined method `webhook_http_code_success=' for #<PactBroker::Configuration:0x00007f05c5953978>
Did you mean?  webhook_http_method_whitelist=
  config.ru:24:in `block (2 levels) in <main>'
```

I guess the "pact-broker" gem has to be updated. Can you give a timeline when it is planned to do it? Or shall I raise a new Pull Request without local testing for now? Merge will be done as soon it is 100% ready. Let me know which way you prefer. Thanks.

**Comment by bethesque** [comment]
I need to do a release of the pact_broker. There's one bug I've just found that I need to fix first but I'll try and get it out today.

**Comment by bethesque** [comment]
Latest release is out.

**Comment by pitschr** [comment]
so fast ... thank you

**Comment by pitschr** [comment]
@bethesque , any chance/timeline to release the 2.78.0 of pact broker which includes the bug fix for http code success check. Then I can continue with this ticket. Thank you.

**Comment by bethesque** [comment]
Oh, of course, done. Thanks!

**Comment by pitschr** [comment]
This ticket can be closed. The docker image `pactfoundation/pact-broker:2.78.1.1` now supports `PACT_BROKER_WEBHOOK_HTTP_CODE_SUCCESS`

**Comment by bethesque** [comment]
Thanks for work on this @pitschr. Much appreciated.
