### ISSUE TITLE
Security vulnerabilities 

### ISSUE THREAD

**Issue by praveen-em** [pact-foundation/pact-broker-docker#65]
# Pre issue-raising checklist

I have already (please mark the applicable with an `x`):

* [x] Confirmed this is the right place to raise the issue - only issues related to the Dockerization of the Pact Broker should be raised here. Issues related to the Pact Broker application itself should be raised in the [Pact Broker](https://github.com/pact-foundation/pact_broker) project.
* [x] Upgraded to the latest Pact Broker Docker image OR
* [ ] Checked the [CHANGELOG](/CHANGELOG.md) to see if the issue I am about to raise has been fixed
* [ ] Read the [Troubleshooting](https://github.com/pact-foundation/pact-broker-docker/wiki/Troubleshooting) page

## Software versions
* **pact-broker docker version:** 2.87.0.2

## Expected behaviour
No security vulnerabilities in the image. 

## Actual behaviour
JFrog's XRay scanner blocks the image because of security vulnerabilities (see attached list). Looks like most of them can be fixed by upgrading to latest libraries. I could give it a try if it was java but I am not very close to Ruby. So, leaving it to experts in the community to take a look.

[Docker_pactfoundation-pact-broker-2.87.0.2_Security_Export.pdf](https://github.com/pact-foundation/pact-broker-docker/files/7322285/Docker_pactfoundation-pact-broker-2.87.0.2_Security_Export.pdf)

## Steps to reproduce
NA

## Relevent log files
NA

**Comment by bethesque** [comment]
The other day I enabled Snyk as well, and this is the only vulnerability it has picked up. There's no fix for this one yet, but it seems it's only relevant if there's a content proxy caching things in the middle.

<img width="1145" alt="Screen Shot 2021-10-12 at 9 17 24 am" src="https://user-images.githubusercontent.com/446228/136861986-94a9ebee-d6d4-4951-b80a-88c8c8b98424.png">
