### ISSUE TITLE
Fixes to security vulnerability issue

### ISSUE THREAD

**Issue by mileyd** [pact-foundation/pact-broker-docker#73]
Hi Team 

I raised an issue a while ago about security vulnerabilities our scanner uncovered in pact-broker-docker. At the time @bethesque issued a request for help. One of our team has picked it up and created a PR containing the necessary fixes to resolve the issue. 

Would it be possible for someone to merge the changes into master, and then arrange for a new version of pact-broker-docker to be released. 

For details of the original issue raised please see:
https://github.com/pact-foundation/pact-broker-docker/issues/69

For the request for help from @bethesque which was responded to please see:
https://github.com/pact-foundation/pact_broker/issues/523

For details of the PR please see:
https://github.com/pact-foundation/pact_broker/pull/542

Thanks a lot.

Dean Miley

**Comment by YOU54F** [comment]
@mileyd a new release is out, please raise a new issue if you find anything new

Thanks!
