### ISSUE TITLE
out of sync readme for published docker image, compared to website?

### ISSUE THREAD

**Issue by YOU54F** [pact-foundation/pact-broker-docker#85]
We have two docker images for PB

1. `dius/pact-broker` https://hub.docker.com/r/dius/pact-broker/
2. `pactfoundation/pact-broker` https://hub.docker.com/r/pactfoundation/pact-broker/

The [readme](https://hub.docker.com/r/dius/pact-broker/) on Docker for the DiUS image lines up with the [website](https://docs.pact.io/pact_broker/docker_images/dius)

The [readme](https://hub.docker.com/r/pactfoundation/pact-broker/) on Docker for the pactfoundation image _doesn't_ line up with the [website](https://docs.pact.io/pact_broker/docker_images/pactfoundation).
- It instead appears to be a copy of the dius image, with the image name changed, and is missing information compared to the website.

**Comment by mefellows** [comment]
I'm looking at the pactfoundation readme and the docs website and they look correct to me. One give away is that they both have the Kubernetes section, which isn't present on the DiUS one:

<img width="1031" alt="Screen Shot 2022-10-12 at 8 12 45 am" src="https://user-images.githubusercontent.com/53900/195199370-68c1b3f1-c2df-4bdd-956c-e1dcb38164b1.png">
<img width="1358" alt="Screen Shot 2022-10-12 at 8 13 06 am" src="https://user-images.githubusercontent.com/53900/195199423-654dfdc0-6316-40f4-bd65-480ec28d55ef.png">

What am I missing?

**Comment by YOU54F** [comment]
Section here on the website titled Authentication

https://docs.pact.io/pact_broker/docker_images/pactfoundation#authentication

It doesn't appear on 

https://hub.docker.com/r/pactfoundation/pact-broker/

there is a similar section titled 

Using basic auth

Which looked to be the same as

https://docs.pact.io/pact_broker/docker_images/dius#using-basic-auth

I didn't dig too much further (I was answering another tangibly related query which got me looking across the two readmes) so this is more of a cookie trail for a later investigation

**Comment by mefellows** [comment]
Ah you're right! Interesting, my guess is some sync isn't working as expected. Good pickup (as always) :)

**Comment by bethesque** [comment]
The docs sync is currently broken since all my tokens got revoked by GitHub last year. I have a ticket in jira to fix them all.

**Comment by bethesque** [comment]
Fixed.
