### ISSUE TITLE
Upgrade Bundler to at least 2.2.33

### ISSUE THREAD

**Issue by jorander** [pact-foundation/pact-broker-docker#93]
# Pre issue-raising checklist

I have already (please mark the applicable with an `x`):

* [X] Confirmed this is the right place to raise the issue - only issues related to the Dockerization of the Pact Broker should be raised here. Issues related to the Pact Broker application itself should be raised in the [Pact Broker](https://github.com/pact-foundation/pact_broker) project.
* [X] Upgraded to the latest Pact Broker Docker image OR
* [X] Checked the [CHANGELOG](/CHANGELOG.md) to see if the issue I am about to raise has been fixed
* [X] Read the [Troubleshooting](https://github.com/pact-foundation/pact-broker-docker/wiki/Troubleshooting) page

## Software versions

* **pact-broker docker version:** 2.105.0.1

## Expected behaviour

No known vulnerabilities.

## Actual behaviour

Bundler 2.1.4 contains two vulnerabilities fixed in later versions (at least version 2.2.33):
* https://bundler.io/blog/2021/02/15/a-more-secure-bundler-we-fixed-our-source-priorities.html
* https://github.com/rubygems/rubygems/security/advisories/GHSA-fj7f-vq84-fh43

## Steps to reproduce

Security scan provided by [Jfrog Xray](https://jfrog.com/xray/).

## Relevent log files

N/A

**Comment by bethesque** [comment]
Released in tag 2.106.0.0
